name: code
description: "MoveCS è l’app che ti mostra tutte le fermate e gli orari dei bus di Cosenza in modo semplice e veloce. Consulta la mappa, trova le fermate vicine, guarda le prossime corse e pianifica i tuoi spostamenti in pochi secondi. Tutto ciò che ti serve per muoverti in città, sempre a portata di mano"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
