// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIQPW1Mt4d_8mBNglvAY4sJ6SzeLgbIFY',
    appId: '1:716528318074:web:99752e9a65f030deff6dc3',
    messagingSenderId: '716528318074',
    projectId: 'move-cs',
    authDomain: 'move-cs.firebaseapp.com',
    storageBucket: 'move-cs.firebasestorage.app',
    measurementId: 'G-H37C871NQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-067ivF5Bf_D_7R1iUJVAn2hdUR1KWtc',
    appId: '1:716528318074:android:014adaa4e0a31fcaff6dc3',
    messagingSenderId: '716528318074',
    projectId: 'move-cs',
    storageBucket: 'move-cs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8QXl8wA0BjNI9PFuzOtcEZNTNzQAYOLg',
    appId: '1:716528318074:ios:c5470784c9707b95ff6dc3',
    messagingSenderId: '716528318074',
    projectId: 'move-cs',
    storageBucket: 'move-cs.firebasestorage.app',
    iosBundleId: 'com.example.code',
  );
}
